name: Detekt Analysis

on:
  pull_request:
    branches:
      - main
      - develop  # Добавьте другие ветки по необходимости

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload Detekt SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/detekt/detekt.sarif
