name: Detekt Analysis

on:
  pull_request:
    branches:
      - main
      - develop  # Добавьте другие ветки по необходимости

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.23.7